/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/ng2-img-fallback.module';
import * as import2 from '@angular/core/src/di/injector';
class Ng2ImgFallbackInjector extends import0.NgModuleInjector<import1.Ng2ImgFallback> {
  _Ng2ImgFallback_0:import1.Ng2ImgFallback;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.Ng2ImgFallback {
    this._Ng2ImgFallback_0 = new import1.Ng2ImgFallback();
    return this._Ng2ImgFallback_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2ImgFallback)) { return this._Ng2ImgFallback_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2ImgFallbackNgFactory:import0.NgModuleFactory<import1.Ng2ImgFallback> = new import0.NgModuleFactory(Ng2ImgFallbackInjector,import1.Ng2ImgFallback);